### ISSUE TITLE
What are we code reviewing?

### ISSUE THREAD

**Issue by Joepock123** [fac19/Week8-BFOP#51]
The readme talks about running tests on the server and database? As the back and front end are packaged together it's a little confusing what we're meant to be reviewing as thought the scope of this week was the SPA? Interested to know why the front and back end are merged into one repo.

**Comment by jamesj-0** [comment]
Everything in the public folder :) Check @hannahgooding's Issue

**Comment by Roger-Heathcote** [comment]
@Joepock123 Hannah asked the samequestion. I answered it here...

https://github.com/fac19/Week8-BFOP/issues/46#issuecomment-618919223
